# Generated by Django 5.2.8 on 2025-11-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('translit', models.SlugField(blank=True, default='', max_length=200, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Справочник упражнений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(db_index=True, verbose_name='Дата проведения')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('exercises', models.ManyToManyField(related_name='trainings', to='journal.exercise', verbose_name='Упражнения')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('repetition', models.PositiveSmallIntegerField(verbose_name='Число повторений')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='journal.exercise', verbose_name='Упражнение')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='journal.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
            },
        ),
    ]
