# Generated by Django 5.2.8 on 2025-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='translit',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Транслит'),
        ),
    ]
