# Generated by Django 5.2.8 on 2025-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_exercise_translit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='translit',
            field=models.SlugField(help_text='Заполняется автоматически на основе названия', max_length=200, unique=True, verbose_name='Транслит'),
        ),
    ]
