# Generated by Django 5.2.8 on 2025-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_exercise_translit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
    ]
