# Generated by Django 5.2.8 on 2025-11-22 08:26

from django.db import migrations

DEFAULT_EXERCISES = [
    {
        'name': 'Приседания',
        'translit': 'prisedaniya',
    },
    {
        'name': 'Выпады',
        'translit': 'vypady',
    },
    {
        'name': 'Жим лёжа',
        'translit': 'zhim_lezha',
    },
    {
        'name': 'Тяга штанги в наклоне',
        'translit': 'tyaga_shtangi_v_naklone',
    },
    {
        'name': 'Планка',
        'translit': 'planka',
    },
    {
        'name': 'Подтягивания',
        'translit': 'podtyagivaniya',
    },
    {
        'name': 'Отжимания',
        'translit': 'otzhimaniya',
    },
    {
        'name': 'Становая тяга',
        'translit': 'stanovaya_tyaga',
    },
    {
        'name': 'Подъём гантелей на бицепс',
        'translit': 'podem_ganteley_na_biceps',
    },
    {
        'name': 'Трицепс на блоке',
        'translit': 'triceps_na_bloke',
    },
]


def create_default_exercises(apps, schema_editor):
    """Создать упражнения по умолчанию"""
    Exercise = apps.get_model('journal', 'Exercise')
    for exercise in DEFAULT_EXERCISES:
        Exercise.objects.create(**exercise)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_exerciseset_comment'),
    ]

    operations = [
        migrations.RunPython(create_default_exercises, migrations.RunPython.noop),
    ]
