# Generated by Django 5.2.8 on 2025-11-22 15:42

from django.db import migrations, models


def set_availability_for_users_for_existing_exercises(apps, schema_editor):
    """Установить доступность пользователю для существующих упражнений"""
    Exercise = apps.get_model('journal', 'Exercise')
    Exercise.objects.all().update(available_for_user=True)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20251122_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='available_for_user',
            field=models.BooleanField(default=False, verbose_name='Доступно для выбора пользователю'),
        ),
        migrations.RunPython(set_availability_for_users_for_existing_exercises, migrations.RunPython.noop),
    ]
