# Generated by Django 5.2.8 on 2025-11-29 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_exercise_available_for_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип тренировки',
                'verbose_name_plural': 'Справочник типов тренировок',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.CreateModel(
            name='AthleteTrainingTypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связка Спортсмен - Цвет - Тип тренировки',
                'verbose_name_plural': 'Связки Спортсмен - Цвет - Тип тренировки',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='athlete_training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='journal.athletetrainingtypecolor'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('background_color', models.CharField(help_text='TailwindCSS-стиль', max_length=30, validators=[django.core.validators.RegexValidator(regex='^bg-[a-z]+-\\d+$')], verbose_name='Цвет фона')),
                ('text_color', models.CharField(help_text='TailwindCSS-стиль', max_length=30, validators=[django.core.validators.RegexValidator(regex='^text-[a-z]+-\\d+$')], verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Цветовая схема',
                'verbose_name_plural': 'Справочник цветовых схем',
                'unique_together': {('background_color', 'text_color')},
            },
        ),
        migrations.AddField(
            model_name='athletetrainingtypecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.color'),
        ),
        migrations.AddField(
            model_name='athletetrainingtypecolor',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.trainingtype'),
        ),
    ]
