# Generated by Django 5.2.8 on 2025-11-29 08:40

from django.db import migrations


DEFAULT_TRAINING_TYPES = [
    'Грудь-трицепс',
    'Спина-бицепс',
    'Ноги-плечи',
    'Кардио',
    'Фулбади',
]

DEFAULT_COLORS = [
    {
        'background_color': 'bg-blue-200',
        'text_color': 'bg-blue-600',
    },
    {
        'background_color': 'bg-red-200',
        'text_color': 'bg-red-600',
    },
    {
        'background_color': 'bg-green-200',
        'text_color': 'bg-green-600',
    },
]


def create_training_types(apps, schema_editor):
    """Создать записи TrainingType"""
    TrainingType = apps.get_model('journal', 'TrainingType')
    for training_type in DEFAULT_TRAINING_TYPES:
        TrainingType.objects.create(name=training_type)


def delete_training_types(apps, schema_editor):
    """Удалить записи TrainingType"""
    TrainingType = apps.get_model('journal', 'TrainingType')
    TrainingType.objects.delete()


def create_colors(apps, schema_editor):
    """Создать записи Color"""
    Color = apps.get_model('journal', 'Color')
    for color in DEFAULT_COLORS:
        Color.objects.create(**color)


def delete_colors(apps, schema_editor):
    """Удалить записи Color"""
    Color = apps.get_model('journal', 'Color')
    Color.objects.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_trainingtype_alter_training_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_training_types, delete_training_types),
        migrations.RunPython(create_colors, delete_colors),
    ]
