# Generated by Django 5.2.8 on 2025-12-06 08:09

from django.db import migrations, models


COLOR_NAME_BY_COLOR_TRANSLIT = {
    'blue': 'Синий',
    'green': 'Зеленый',
    'red': 'Красный',
}


def set_name_to_color(apps, schema_editor):
    """Установить название цветам"""
    Color = apps.get_model('journal', 'Color')
    for color_translit, name in COLOR_NAME_BY_COLOR_TRANSLIT.items():
        Color.objects.filter(background_color__icontains=color_translit).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20251129_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Название цвета'),
        ),
        migrations.RunPython(set_name_to_color, migrations.RunPython.noop),
    ]
